package com.gamecore.data.database

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Relation

/**
 * The Aim Lab tables, added in schema version 7.
 *
 * All of them live inside the existing encrypted `gamecore-store` database, so nothing here handles
 * keys or encryption — the SQLCipher passphrase set up in `DatabaseModule` covers these rows exactly as
 * it does the rest. Every one follows the conventions the existing tables set: snake_case `@ColumnInfo`
 * names, autogenerated `Long` ids, enums stored as their `.name` string and parsed back defensively in
 * [AimLabMappers], and — for the two-table layout — no foreign-key cascade (the DAO deletes children in a
 * transaction, because SQLCipher only honours FKs when the per-connection pragma is set).
 *
 * The session row is a summary written once when a run ends; there is no per-frame table, because the
 * high-frequency training data lives in memory during the run and never reaches Room (§18).
 */
@Entity(tableName = "aimlab_sessions", indices = [Index("mode"), Index("started_at")])
data class AimLabSessionEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long,

    @ColumnInfo(name = "mode")
    val mode: String,

    @ColumnInfo(name = "difficulty")
    val difficulty: String,

    @ColumnInfo(name = "started_at")
    val startedAtMillis: Long,

    @ColumnInfo(name = "ended_at")
    val endedAtMillis: Long,

    @ColumnInfo(name = "weapon_name")
    val weaponName: String?,

    @ColumnInfo(name = "sensitivity_name")
    val sensitivityName: String?,

    @ColumnInfo(name = "score")
    val score: Int,

    @ColumnInfo(name = "hits")
    val hits: Int,

    @ColumnInfo(name = "shots")
    val shots: Int,

    @ColumnInfo(name = "targets_missed")
    val targetsMissed: Int,

    @ColumnInfo(name = "reaction_attempts")
    val reactionAttempts: Int,

    @ColumnInfo(name = "reaction_fastest")
    val reactionFastest: Long,

    @ColumnInfo(name = "reaction_slowest")
    val reactionSlowest: Long,

    @ColumnInfo(name = "reaction_avg")
    val reactionAverage: Float,

    @ColumnInfo(name = "reaction_median")
    val reactionMedian: Float,

    @ColumnInfo(name = "avg_acquire")
    val averageAcquireMillis: Float,

    @ColumnInfo(name = "tracking_error_avg")
    val trackingErrorAverage: Float,

    @ColumnInfo(name = "time_on_target")
    val timeOnTargetFraction: Float,

    @ColumnInfo(name = "recoil_compensation")
    val recoilCompensation: Float,

    @ColumnInfo(name = "gyro_stability")
    val gyroStability: Float,

    /**
     * The scoring/rendering generation that produced this row (§6), added in schema version 8.
     *
     * `NOT NULL DEFAULT 1` in the migration: every session that existed before the 3D view was a 2D-arena
     * session, and `SessionSummary.SCORING_VERSION_2D` is 1. New rows write the 3D value. This is what
     * lets history label the old sessions "legacy 2D" and keeps records from ranking a 2D result against
     * a 3D one.
     */
    @ColumnInfo(name = "scoring_version", defaultValue = "1")
    val scoringVersion: Int,
)

/** A training weapon's row. Flat: one column per parameter, including the four recoil fields. */
@Entity(tableName = "aimlab_weapons")
data class AimLabWeaponEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "category")
    val category: String,

    @ColumnInfo(name = "fire_rate_rpm")
    val fireRateRpm: Int,

    @ColumnInfo(name = "magazine_size")
    val magazineSize: Int,

    @ColumnInfo(name = "reload_millis")
    val reloadMillis: Long,

    @ColumnInfo(name = "ads_time_millis")
    val adsTimeMillis: Long,

    @ColumnInfo(name = "movement_penalty")
    val movementPenalty: Float,

    @ColumnInfo(name = "spread")
    val spread: Float,

    @ColumnInfo(name = "vertical_per_shot")
    val verticalPerShot: Float,

    @ColumnInfo(name = "horizontal_per_shot")
    val horizontalPerShot: Float,

    @ColumnInfo(name = "randomness")
    val randomness: Float,

    @ColumnInfo(name = "recovery_per_second")
    val recoveryPerSecond: Float,

    @ColumnInfo(name = "is_built_in")
    val isBuiltIn: Boolean,

    /**
     * How the weapon discharges — `SINGLE`/`BURST`/`AUTO` — added in schema version 10.
     *
     * `NOT NULL DEFAULT 'AUTO'` in the migration: every weapon that existed before fire modes fired
     * automatically, which is what the loop already did, so an old row reads back unchanged.
     */
    @ColumnInfo(name = "fire_mode", defaultValue = "AUTO")
    val fireMode: String = "AUTO",

    /** Rounds per burst when [fireMode] is BURST; `NOT NULL DEFAULT 3`, ignored for the other modes. */
    @ColumnInfo(name = "burst_count", defaultValue = "3")
    val burstCount: Int = 3,
)

/** A sensitivity profile's row. Flat, one column per field. */
@Entity(tableName = "aimlab_sensitivities")
data class AimLabSensitivityEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "preset")
    val preset: String,

    @ColumnInfo(name = "camera_sensitivity")
    val cameraSensitivity: Float,

    @ColumnInfo(name = "ads_multiplier")
    val adsMultiplier: Float,

    @ColumnInfo(name = "gyro_sensitivity")
    val gyroSensitivity: Float,

    @ColumnInfo(name = "gyro_ads_multiplier")
    val gyroAdsMultiplier: Float,

    @ColumnInfo(name = "horizontal_scale")
    val horizontalScale: Float,

    @ColumnInfo(name = "vertical_scale")
    val verticalScale: Float,

    @ColumnInfo(name = "deadzone_percent")
    val deadzonePercent: Int,

    @ColumnInfo(name = "smoothing_percent")
    val smoothingPercent: Int,

    @ColumnInfo(name = "response_exponent")
    val responseExponent: Float,

    @ColumnInfo(name = "invert_x")
    val invertX: Boolean,

    @ColumnInfo(name = "invert_y")
    val invertY: Boolean,
)

/**
 * A control layout's own row; its controls are separate rows in [AimLabControlEntity].
 *
 * Same split — and same reasoning — as `hud_layouts`/`hud_widgets`: rows, not a JSON blob, so the data
 * goes through Room's type checking and an imported layout cannot smuggle a hand-parsed structure past it.
 */
@Entity(tableName = "aimlab_layouts")
data class AimLabLayoutEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "created_at")
    val createdAtMillis: Long,

    @ColumnInfo(name = "updated_at")
    val updatedAtMillis: Long,
)

/**
 * One control on one layout.
 *
 * The primary key is `(layout_id, role)`: a role is unique within a layout — there is one Shoot button —
 * so the pair identifies a control without a surrogate id. No FK cascade, for the reason the class note on
 * [HudWidgetEntity] gives; children are deleted explicitly in the DAO's save/delete transactions.
 */
@Entity(
    tableName = "aimlab_controls",
    primaryKeys = ["layout_id", "role", "orientation"],
    indices = [Index("layout_id")],
)
data class AimLabControlEntity(
    @ColumnInfo(name = "layout_id")
    val layoutId: Long,

    @ColumnInfo(name = "role")
    val role: String,

    @ColumnInfo(name = "x_fraction")
    val xFraction: Float,

    @ColumnInfo(name = "y_fraction")
    val yFraction: Float,

    @ColumnInfo(name = "width_fraction")
    val widthFraction: Float,

    @ColumnInfo(name = "height_fraction")
    val heightFraction: Float,

    @ColumnInfo(name = "opacity_percent")
    val opacityPercent: Int,

    @ColumnInfo(name = "shape")
    val shape: String,

    @ColumnInfo(name = "enabled")
    val enabled: Boolean,

    /**
     * Which orientation this placement belongs to, added in schema version 9 for landscape support.
     *
     * A layout now stores two arrangements of the same controls: one for portrait, one for landscape,
     * each a set of fractions of that orientation's safe area. The value is a [ControlOrientation] name
     * (`PORTRAIT`/`LANDSCAPE`). `NOT NULL DEFAULT 'PORTRAIT'` in the migration, so every control that
     * existed before version 9 becomes the layout's portrait set — which is what it always was. The
     * primary key gains this column so the two orientations coexist for one role in one layout.
     */
    @ColumnInfo(name = "orientation", defaultValue = "PORTRAIT")
    val orientation: String = "PORTRAIT",
)

/**
 * A layout and all its controls in one query, the single source the list, the editor and the training
 * screen all read through (§bug-fix): the "N of M controls enabled" count and the drawn overlay are then
 * the same real rows, never an editor-only in-memory preset on one side and empty rows on the other.
 */
data class AimLabLayoutWithControls(
    @Embedded val layout: AimLabLayoutEntity,
    @Relation(parentColumn = "id", entityColumn = "layout_id")
    val controls: List<AimLabControlEntity>,
)

/**
 * A personal record row, one per (mode, difficulty, weapon, metric).
 *
 * A stored table rather than a query-time derivation because a record carries the value it *beat*
 * ([previousValue]) and the moment it was set, neither of which survives recomputation from sessions. The
 * unique index on the four key columns is what makes "is this a new record for this combination" a single
 * upsert. `weapon_name` is nullable and part of the key, so weapon-less modes share one slot.
 */
@Entity(
    tableName = "aimlab_records",
    indices = [
        Index(
            value = ["mode", "difficulty", "weapon_name", "metric", "scoring_version"],
            unique = true,
        ),
    ],
)
data class AimLabRecordEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long,

    @ColumnInfo(name = "mode")
    val mode: String,

    @ColumnInfo(name = "difficulty")
    val difficulty: String,

    @ColumnInfo(name = "weapon_name")
    val weaponName: String?,

    @ColumnInfo(name = "metric")
    val metric: String,

    @ColumnInfo(name = "value")
    val value: Float,

    @ColumnInfo(name = "previous_value")
    val previousValue: Float?,

    @ColumnInfo(name = "achieved_at")
    val achievedAtMillis: Long,

    /**
     * The scoring generation this record belongs to (§6), added in schema version 8 and part of the
     * unique key. A 3D record and a 2D record for the same mode/difficulty/weapon/metric are different
     * measurements and coexist as separate rows; the repository only ever challenges a record of the same
     * version. `NOT NULL DEFAULT 1`, so every pre-existing record is a legacy-2D record.
     */
    @ColumnInfo(name = "scoring_version", defaultValue = "1")
    val scoringVersion: Int,
)
