package com.gamecore.data.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A backed-up config file's row (schema version 13).
 *
 * The bytes themselves are not here — a config file can be any size and any content, and a 2 MiB
 * blob column read on every list would be the wrong shape for a table the browser scans. The bytes
 * live on GameCore's own disk under `filesDir/configbackups/<pkg>/`; this row is the ledger that
 * records *that* a file was backed up, where the copy is, and enough about it to warn, restore and
 * explain without opening it.
 *
 * A backup is keyed for lookup by the file it came from — [packageName], [userId], [relativePath],
 * the same three parts [com.gamecore.core.shizuku] builds a validated path from — but its primary key
 * is an autogenerated id, because one file has one [ConfigBackupKind.ORIGINAL] and any number of
 * [ConfigBackupKind.CHECKPOINT]s over time. The "never overwritten" rule for the original is enforced
 * at [backupPath], which is unique: the original's path is deterministic per file, so an
 * `INSERT … ON CONFLICT IGNORE` on a path that already exists keeps the first copy rather than
 * replacing it — the same first-write-wins discipline [RestorePointEntity] uses on its key.
 *
 * Deliberately no foreign key to `game_profiles`: a backup outlives the profile. Deleting a profile
 * is the user saying "stop optimising this game", not "throw away the original of a file I edited",
 * and the two must not be the same action. Cleanup, when it is wanted, is the explicit
 * `deleteForApp` path, not a cascade — and cascades are avoided here anyway for the reason
 * [HudWidgetEntity] documents.
 */
@Entity(
    tableName = "config_backups",
    indices = [
        // The original's path is deterministic, so a unique path is what makes "never overwritten"
        // a database invariant rather than a convention a caller has to remember.
        Index(value = ["backup_path"], unique = true),
        // The browser and the drift check both look up every backup of one file, so the three parts
        // that name a file are indexed together.
        Index(value = ["package_name", "user_id", "relative_path"]),
    ],
)
data class ConfigBackupEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long,

    @ColumnInfo(name = "package_name")
    val packageName: String,

    /** The emulated-storage user id the file lives under; part of a file's identity, not decoration. */
    @ColumnInfo(name = "user_id")
    val userId: Int,

    /** The file's path relative to the game's `files` dir — what the shell path builder is given. */
    @ColumnInfo(name = "relative_path")
    val relativePath: String,

    /** Absolute path of the stored copy on GameCore's own disk. Unique — see the class doc. */
    @ColumnInfo(name = "backup_path")
    val backupPath: String,

    /** [com.gamecore.core.model.ConfigBackupKind] by name, parsed back defensively in the mapper. */
    @ColumnInfo(name = "kind")
    val kind: String,

    /** The user's label for a checkpoint, sanitised on the way in; null for an original. */
    @ColumnInfo(name = "label")
    val label: String?,

    @ColumnInfo(name = "size_bytes")
    val sizeBytes: Long,

    /** Hex SHA-256 of the backed-up bytes, or null when it was not computed. */
    @ColumnInfo(name = "sha256")
    val sha256: String?,

    /** The game's `lastUpdateTime` when this was taken, for the update-drift check; null if unknown. */
    @ColumnInfo(name = "source_last_update_time")
    val sourceLastUpdateTime: Long?,

    @ColumnInfo(name = "created_at")
    val createdAtMillis: Long,
)
