package com.gamecore.core.model

/**
 * Why a stored config backup exists — the untouched original, or a snapshot the user asked for.
 *
 * The distinction is not cosmetic: it decides what may be deleted and what may not. An [ORIGINAL] is
 * the one copy of a file as it was *before* GameCore ever wrote to it, taken on the first edit and
 * never overwritten (§A6). It is the floor the user falls back to when an edit — or a run of edits —
 * turns out to have broken the game, so nothing in the app deletes it while the file still exists to
 * restore. A [CHECKPOINT] is a copy the user took deliberately at a point they liked; there can be
 * many, they carry a label, and removing one loses only a bookmark, not the safety net.
 *
 * Stored as the enum name like every other enum that reaches the database, and parsed back by name
 * with a fallback to [ORIGINAL] rather than [valueOf] — see [com.gamecore.data.database.ConfigBackupMappers].
 * The fallback direction is chosen so that a row from a newer build, or a hand-edited one, is treated
 * as the copy that must be *kept* rather than the one that may be discarded.
 */
enum class ConfigBackupKind {

    /** The file as it was before the first edit. One per file, never overwritten, never auto-deleted. */
    ORIGINAL,

    /** A snapshot the user took at a point they wanted to be able to come back to. */
    CHECKPOINT,
}

/**
 * One backed-up config file, as the app reasons about it.
 *
 * A backup is identified by the file it came from — [packageName] + [userId] + [relativePath], the
 * same three parts the privileged shell builds a path from — and stored as bytes on GameCore's own
 * disk at [backupPath], outside the game's sandbox so an uninstall or a wipe of the game does not take
 * the safety net with it. It is deliberately independent of any [GameProfile]: deleting a profile must
 * not delete the original copy of a file the user may still want back.
 *
 * [sourceLastUpdateTime] is the game's `PackageInfo.lastUpdateTime` at the moment the backup was taken.
 * It is what a later update-drift check (§A9) compares against: if the game has been updated since, a
 * config saved against the old build may no longer fit the new one, and the warning is only honest if
 * there is a recorded "as of when" to compare to. Nullable because the package manager does not always
 * surface it, and a backup with no recorded stamp simply cannot raise a drift warning — which is the
 * safe direction to be unsure in.
 *
 * [sha256] is the hex digest of the backed-up bytes, so a restore or the editor can tell whether the
 * live file still matches this copy without reading both in full. Nullable so a row that predates the
 * digest, or one written where hashing was skipped, reads as "unknown" rather than "mismatched".
 */
data class ConfigBackup(
    val id: Long,
    val packageName: String,
    val userId: Int,
    val relativePath: String,
    val backupPath: String,
    val kind: ConfigBackupKind,
    val label: String?,
    val sizeBytes: Long,
    val sha256: String?,
    val sourceLastUpdateTime: Long?,
    val createdAtMillis: Long,
) {
    /** True for the untouched original — the copy the app must never delete while it can be restored. */
    val isOriginal: Boolean get() = kind == ConfigBackupKind.ORIGINAL

    companion object {
        /** Not autoGenerated yet: the id a new backup carries until Room assigns its rowid. */
        const val UNSAVED_ID = 0L
    }
}
